"""
KALSHI SHADOW MODE — WebSocket edition.

WebSocket-based, authenticated. No polling. Real-time book deltas + trades
on the same latency profile as production bots (~50-200ms matching engine -> us).

Architecture:
  - Auth:           RSA-PSS-SHA256 signature headers for every connection
  - Market WS:      subscribes to orderbook_delta + trade channels for our 15 markets
  - Book state:     maintains local {bid_level: size, ask_level: size} per market
                    rebuilt on snapshot, updated incrementally via deltas
  - Quote logic:    runs on every book update — computes what we'd quote
  - Fill detection: on every trade message, check if trade price crosses our
                    virtual quote. Requires taker_side match + size > 0.
  - Rewards proxy:  records distance-from-mid + size at every book update,
                    approximating Kalshi's per-second snapshot scoring.

Reads candidates from kalshi_candidates_v2.json (generated by diag_kalshi_v2.py).

Outputs: same CSVs as REST version — kalshi_shadow_fills.csv, _quotes.csv, _rewards.csv
"""

import base64
import csv
import json
import os
import signal
import threading
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Optional

try:
    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import padding
except ImportError:
    raise SystemExit("Missing dependency. Run:\n  pip install cryptography --break-system-packages")

try:
    import websocket
except ImportError:
    raise SystemExit("Missing dependency. Run:\n  pip install websocket-client --break-system-packages")

# ── Config ─────────────────────────────────────────────────────────
KEY_ID = os.environ.get("KALSHI_KEY_ID", "")
PRIVATE_KEY_PATH = os.environ.get("KALSHI_PRIVATE_KEY_PATH", "")
API_BASE = os.environ.get("KALSHI_API_BASE", "https://api.elections.kalshi.com/trade-api/v2")
WS_URL = "wss://api.elections.kalshi.com/trade-api/ws/v2"

CANDIDATES_PATH = os.path.join(os.path.dirname(__file__), "kalshi_candidates_v2.json")
TOP_N_MARKETS = int(os.environ.get("SHADOW_TOP_N", "15"))
MIN_SPREAD_TICKS = 3
QUOTE_SIZE_CONTRACTS = 100
CLIP_USD = 100.0

# ── Kalshi fee model ──────────────────────────────────────────────
# Fee = rate × contracts × P × (1-P) per side
# Maker: limit order that rests in the book (doesn't cross). Cheaper.
# Taker: order that crosses the spread and executes immediately. Expensive.
# Fees are highest at P=0.5 (0.25 coefficient) and drop sharply toward tails.
FEE_RATE_MAKER = 0.0175
FEE_RATE_TAKER = 0.07


def compute_fee(contracts: float, price: float, is_taker: bool) -> float:
    """Kalshi per-side fee: rate × contracts × P × (1-P)."""
    rate = FEE_RATE_TAKER if is_taker else FEE_RATE_MAKER
    return rate * contracts * price * (1 - price)

# ── Portfolio risk controls (v2) ──────────────────────────────────
# Global cap: hard ceiling across all markets combined (no longer purely per-market).
GLOBAL_INVENTORY_CAP_USD = float(os.environ.get("GLOBAL_INV_CAP_USD", "150.0"))

# Turnover gate: if a market has inventory > 0 and hasn't sold in TURNOVER_WINDOW_MIN,
# switch to liquidate mode (sell at bid, no new buys).
TURNOVER_WINDOW_MIN = 60
TURNOVER_MIN_SELLS_PER_WINDOW = 2

# Category rules: matched by ticker prefix. cap_multiplier applied to CLIP_USD per-market.
# jump_risk categories disabled entirely (cap_multiplier=0 → no quotes).
CATEGORY_RULES = [
    ("golf",             ["KXPGATOUR", "KXLPGATOUR", "KXKFTOUR"],                       1.0),
    ("political_binary", ["KXNEXTAG", "KXTRUMPADMIN", "KXKASHOUT", "KXHEGSETHOUT"],     0.15),
    ("jump_risk",        ["KXUSAIRANAGREEMENT", "KXGOVTSHUTLENGTH", "KXTEAMSINNBAF"],   0.0),
    ("sports_other",     ["KXMARMAD", "KXPERUPRES"],                                    0.3),
]


def classify_market(ticker: str):
    """Return (category_name, cap_multiplier)."""
    for cat, prefixes, mult in CATEGORY_RULES:
        for p in prefixes:
            if ticker.startswith(p):
                return cat, mult
    return "default", 0.5

TRADES_LOG = os.path.join(os.path.dirname(__file__), "kalshi_shadow_fills.csv")
QUOTES_LOG = os.path.join(os.path.dirname(__file__), "kalshi_shadow_quotes.csv")
REWARDS_LOG = os.path.join(os.path.dirname(__file__), "kalshi_shadow_rewards.csv")

_STOP = False
_LOCK = threading.Lock()
_START = time.time()


def handle_stop(signum, frame):
    global _STOP
    _STOP = True
    print("\nshutdown requested, closing WS...", flush=True)


signal.signal(signal.SIGINT, handle_stop)
signal.signal(signal.SIGTERM, handle_stop)


# ── Auth ───────────────────────────────────────────────────────────

def load_private_key():
    if not PRIVATE_KEY_PATH or not os.path.exists(PRIVATE_KEY_PATH):
        raise SystemExit(f"Private key not found at {PRIVATE_KEY_PATH}")
    with open(PRIVATE_KEY_PATH, "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None, backend=default_backend())


def sign_request(private_key, method: str, path: str) -> Dict[str, str]:
    """Generate Kalshi auth headers for a request."""
    ts_ms = str(int(time.time() * 1000))
    msg = (ts_ms + method.upper() + path).encode("utf-8")
    sig = private_key.sign(
        msg,
        padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.DIGEST_LENGTH),
        hashes.SHA256(),
    )
    return {
        "KALSHI-ACCESS-KEY": KEY_ID,
        "KALSHI-ACCESS-TIMESTAMP": ts_ms,
        "KALSHI-ACCESS-SIGNATURE": base64.b64encode(sig).decode("utf-8"),
    }


# ── Market state ───────────────────────────────────────────────────

@dataclass
class MarketShadow:
    ticker: str
    title: str
    tick: float
    vol_24h: float
    # Category + cap (assigned at load)
    category: str = "default"
    cap_multiplier: float = 0.5
    # Book state — prices stored in dollars
    yes_levels: Dict[float, float] = field(default_factory=dict)
    no_levels: Dict[float, float] = field(default_factory=dict)
    best_bid: float = 0.0
    best_ask: float = 0.0
    best_bid_size: int = 0
    best_ask_size: int = 0
    # Our virtual quotes (dollars)
    our_buy_px: float = 0.0
    our_sell_px: float = 0.0
    buy_armed: bool = True
    sell_armed: bool = True
    # Virtual inventory / P&L
    inventory: float = 0.0
    cost_basis: float = 0.0
    realized_pnl: float = 0.0
    fills_buy: int = 0
    fills_sell: int = 0
    # Counters
    book_updates: int = 0
    trades_seen: int = 0
    # Rewards proxy
    cumulative_distance_score: float = 0.0
    score_samples: int = 0
    # Turnover tracking (sell timestamps, for auto-liquidation detection)
    recent_sell_ts: list = field(default_factory=list)
    liquidating: bool = False
    # Fee tracking (separated to see true net)
    fees_paid_maker: float = 0.0
    fees_paid_taker: float = 0.0


STATES: Dict[str, MarketShadow] = {}


# ── Logging ────────────────────────────────────────────────────────

def ensure_logs():
    for path, header in [
        (TRADES_LOG, ["timestamp", "ticker", "side", "fill_px", "size",
                      "inventory_after", "realized_pnl", "title"]),
        (QUOTES_LOG, ["timestamp", "ticker", "best_bid", "best_ask",
                      "our_buy", "our_sell", "inventory", "realized_pnl"]),
        (REWARDS_LOG, ["timestamp", "ticker", "distance_from_mid_bid",
                       "distance_from_mid_ask", "normalized_score"]),
    ]:
        if not os.path.exists(path):
            with open(path, "w", newline="") as f:
                csv.writer(f).writerow(header)


# ── Book update handlers ───────────────────────────────────────────

def recompute_top_of_book(s: MarketShadow):
    """Rebuild best_bid/best_ask from level dicts. Prices are stored in dollars directly."""
    yes_active = {p: sz for p, sz in s.yes_levels.items() if sz > 0}
    no_active = {p: sz for p, sz in s.no_levels.items() if sz > 0}
    if yes_active:
        best_yes_dollars = max(yes_active.keys())
        s.best_bid = best_yes_dollars
        s.best_bid_size = int(yes_active[best_yes_dollars])
    else:
        s.best_bid = 0.0
        s.best_bid_size = 0
    if no_active:
        best_no_dollars = max(no_active.keys())
        # YES ask = 1.0 - NO bid (complement)
        s.best_ask = round(1.0 - best_no_dollars, 6)
        s.best_ask_size = int(no_active[best_no_dollars])
    else:
        s.best_ask = 0.0
        s.best_ask_size = 0


def _parse_level(lvl):
    """Parse a book level. Kalshi WS format: ["0.0010", "1000.00"] (dollars, size as strings).
    Returns (price_dollars_float, size_float) or None."""
    if isinstance(lvl, list) and len(lvl) >= 2:
        try:
            return float(lvl[0]), float(lvl[1])
        except (ValueError, TypeError):
            return None
    if isinstance(lvl, dict):
        p = lvl.get("price_dollars") or lvl.get("price") or lvl.get("p")
        sz = lvl.get("size") or lvl.get("quantity") or lvl.get("s")
        if p is None or sz is None:
            return None
        try:
            return float(p), float(sz)
        except (ValueError, TypeError):
            return None
    return None


# One-shot debug: dump first message of each type so we can see raw format
_DEBUG_SEEN_TYPES: set = set()


def _debug_dump(msg_type: str, payload: dict):
    if msg_type in _DEBUG_SEEN_TYPES:
        return
    _DEBUG_SEEN_TYPES.add(msg_type)
    try:
        print(f"  [debug first {msg_type}] {json.dumps(payload)[:500]}", flush=True)
    except Exception:
        pass


def _price_key(price_dollars: float, tick: float) -> float:
    """Snap to the market's tick grid so delta lookups match snapshot keys."""
    return round(round(price_dollars / tick) * tick, 6)


def apply_orderbook_snapshot(s: MarketShadow, snapshot: dict):
    """Reset the local book from a full snapshot message."""
    s.yes_levels = {}
    s.no_levels = {}
    yes_raw = snapshot.get("yes_dollars_fp") or snapshot.get("yes") or []
    no_raw = snapshot.get("no_dollars_fp") or snapshot.get("no") or []
    for lvl in yes_raw:
        parsed = _parse_level(lvl)
        if parsed:
            p_dollars, sz = parsed
            if sz > 0:
                s.yes_levels[_price_key(p_dollars, s.tick)] = sz
    for lvl in no_raw:
        parsed = _parse_level(lvl)
        if parsed:
            p_dollars, sz = parsed
            if sz > 0:
                s.no_levels[_price_key(p_dollars, s.tick)] = sz
    recompute_top_of_book(s)


def apply_orderbook_delta(s: MarketShadow, delta: dict):
    """Incremental update. Kalshi: {price_dollars: "0.6900", delta_fp: "67.57", side: "yes"}."""
    price = delta.get("price_dollars") or delta.get("price") or delta.get("p")
    delta_size = None
    for k in ("delta_fp", "delta", "d", "quantity_delta", "size_delta"):
        if k in delta:
            delta_size = delta[k]
            break
    side = (delta.get("side") or delta.get("s") or "").lower()
    if price is None or delta_size is None:
        return
    try:
        p_dollars = float(price)
        d = float(delta_size)
    except (ValueError, TypeError):
        return
    key = _price_key(p_dollars, s.tick)
    target = s.yes_levels if side == "yes" else s.no_levels if side == "no" else None
    if target is None:
        return
    current = target.get(key, 0.0)
    new_size = current + d
    if new_size <= 0:
        target.pop(key, None)
    else:
        target[key] = new_size
    recompute_top_of_book(s)


# ── Quoting (Avellaneda-Stoikov inspired, inventory-aware) ─────────
#
# Simplified A-S: quote skew + spread widening based on inventory.
#   reservation_price = mid - γ * (q / q_max) * spread
#   skew shifts both bid+ask toward lower prices when we're long (encouraging sells)
#   spread widens as inventory grows (adverse-selection protection)
#
# Full A-S requires calibrating σ (volatility) and κ (arrival rate) per market.
# We start with fixed γ; later we'll calibrate from live tick data.

GAMMA = 0.30          # risk aversion — higher = more skew per unit inventory
Q_MAX_DOLLARS = CLIP_USD  # max inventory dollar exposure (already defined as 100)
SPREAD_WIDEN_MAX_PCT = 0.25  # max % extra spread widening at full inventory


def _global_inventory_usd() -> float:
    """Sum inventory × mid across all markets (approximation of total open exposure)."""
    total = 0.0
    for st in STATES.values():
        if st.inventory <= 0:
            continue
        mid = (st.best_bid + st.best_ask) / 2.0 if st.best_bid > 0 and st.best_ask > 0 else st.cost_basis
        total += st.inventory * max(mid, 0.001)
    return total


def compute_quotes(s: MarketShadow):
    tick = s.tick

    # ── Category gate: jump_risk markets disabled from new buys ───
    # If we have residual inventory from before the gate was active, liquidate it.
    if s.cap_multiplier <= 0.0:
        s.our_buy_px = 0.0
        if s.inventory > 0 and s.best_bid > 0:
            s.our_sell_px = round(max(s.best_bid, tick), 4)
            if not s.liquidating:
                print(f"  🟡 JUMP-RISK LIQUIDATE {s.ticker[:32]}  inv={s.inventory:.0f}", flush=True)
                s.liquidating = True
        else:
            s.our_sell_px = 0.0
        return

    # Book not ready
    if s.best_bid <= 0 or s.best_ask <= 0 or s.best_ask <= s.best_bid:
        s.our_buy_px = 0.0
        s.our_sell_px = 0.0
        return

    mid = (s.best_bid + s.best_ask) / 2.0
    base_spread = s.best_ask - s.best_bid

    # ── Turnover gate: after runtime >= TURNOVER_WINDOW_MIN, if we have
    # inventory but haven't sold TURNOVER_MIN_SELLS_PER_WINDOW times in the
    # last window → enter liquidation mode.
    runtime_min = (time.time() - _START) / 60.0
    if runtime_min >= TURNOVER_WINDOW_MIN and s.inventory > 0:
        now = time.time()
        s.recent_sell_ts = [t for t in s.recent_sell_ts if now - t < TURNOVER_WINDOW_MIN * 60]
        if len(s.recent_sell_ts) < TURNOVER_MIN_SELLS_PER_WINDOW:
            if not s.liquidating:
                print(f"  🟡 LIQUIDATING {s.ticker[:32]}  inv={s.inventory:.0f} (no turnover, dumping)", flush=True)
                s.liquidating = True
            s.our_buy_px = 0.0
            # Sell aggressively at bid (take the cross)
            s.our_sell_px = round(max(s.best_bid, tick), 4)
            return
    # If we hit 0 inventory while liquidating, clear the flag
    if s.liquidating and s.inventory <= 0:
        s.liquidating = False

    # Baseline: 1 tick inside each side if spread >= 2 ticks, else join queue
    if base_spread < 2 * tick - 1e-9:
        raw_buy = s.best_bid
        raw_sell = s.best_ask
    else:
        raw_buy = s.best_bid + tick
        raw_sell = s.best_ask - tick

    # Category-adjusted per-market cap
    market_cap_usd = CLIP_USD * s.cap_multiplier
    inv_dollars = s.inventory * max(mid, 0.01)

    # Inventory skew (A-S)
    q_norm = inv_dollars / max(market_cap_usd, 1.0)
    q_norm = max(-1.0, min(1.0, q_norm))
    skew = GAMMA * q_norm * base_spread
    extra_widen = SPREAD_WIDEN_MAX_PCT * abs(q_norm) * base_spread / 2.0

    buy_px = raw_buy - skew - extra_widen
    sell_px = raw_sell - skew + extra_widen

    def snap(px):
        return round(round(px / tick) * tick, 4)

    s.our_buy_px = snap(buy_px)
    s.our_sell_px = snap(sell_px)

    if s.our_buy_px >= s.our_sell_px:
        s.our_buy_px = 0.0; s.our_sell_px = 0.0; return
    if s.our_buy_px <= 0 or s.our_sell_px >= 1.0:
        s.our_buy_px = 0.0; s.our_sell_px = 0.0; return

    # ── Per-market inventory cap ──────────────────────────────────
    if inv_dollars >= market_cap_usd:
        s.our_buy_px = 0.0

    # ── GLOBAL inventory cap (portfolio-level) ────────────────────
    if _global_inventory_usd() >= GLOBAL_INVENTORY_CAP_USD:
        s.our_buy_px = 0.0

    # Don't sell if flat
    if s.inventory <= 0:
        s.our_sell_px = 0.0

    if not s.buy_armed and s.our_buy_px > 0 and s.best_ask > s.our_buy_px + tick:
        s.buy_armed = True
    if not s.sell_armed and s.our_sell_px > 0 and s.best_bid < s.our_sell_px - tick:
        s.sell_armed = True


def log_quote_snapshot(s: MarketShadow):
    with open(QUOTES_LOG, "a", newline="") as f:
        csv.writer(f).writerow([
            datetime.now(timezone.utc).isoformat(timespec="milliseconds"),
            s.ticker, f"{s.best_bid:.4f}", f"{s.best_ask:.4f}",
            f"{s.our_buy_px:.4f}", f"{s.our_sell_px:.4f}",
            f"{s.inventory:.0f}", f"{s.realized_pnl:.2f}",
        ])


def log_rewards(s: MarketShadow):
    if s.best_bid <= 0 or s.best_ask <= 0:
        return
    mid = (s.best_bid + s.best_ask) / 2.0
    bid_dist = (mid - s.our_buy_px) if s.our_buy_px > 0 else 999
    ask_dist = (s.our_sell_px - mid) if s.our_sell_px > 0 else 999
    norm = ((bid_dist + ask_dist) / 2.0) / max(s.tick, 1e-9)
    s.cumulative_distance_score += norm
    s.score_samples += 1
    with open(REWARDS_LOG, "a", newline="") as f:
        csv.writer(f).writerow([
            datetime.now(timezone.utc).isoformat(timespec="milliseconds"),
            s.ticker, f"{bid_dist:.4f}", f"{ask_dist:.4f}", f"{norm:.2f}",
        ])


# ── Fill detection ─────────────────────────────────────────────────

def handle_trade(s: MarketShadow, trade: dict):
    """Check if a real trade crosses our virtual quote.
    Kalshi trade schema: {yes_price_dollars: "0.5100", count_fp: "1.00", taker_side: "yes"}"""
    s.trades_seen += 1
    yes_px_raw = trade.get("yes_price_dollars") or trade.get("yes_price")
    count_raw = trade.get("count_fp") or trade.get("count") or trade.get("size")
    taker_side = (trade.get("taker_side") or "").lower()
    if yes_px_raw is None or count_raw is None:
        return
    try:
        yes_px = float(yes_px_raw)
        size = float(count_raw)
    except (ValueError, TypeError):
        return
    if yes_px <= 0 or yes_px >= 1.0 or size <= 0:
        return

    # BUY fill: taker sold yes at our_buy_px or lower
    if (s.buy_armed and s.our_buy_px > 0 and taker_side == "no"
            and yes_px <= s.our_buy_px + 1e-9):
        # Size-cap the fill to respect per-market AND global caps.
        # Simulates the fact that a real posted order would have had a specific size.
        mid_for_size = (s.best_bid + s.best_ask) / 2.0 if s.best_ask > 0 else s.our_buy_px
        market_cap_usd = CLIP_USD * s.cap_multiplier
        inv_dollars = s.inventory * max(mid_for_size, 0.001)
        per_mkt_avail = max(market_cap_usd - inv_dollars, 0.0)
        global_avail = max(GLOBAL_INVENTORY_CAP_USD - _global_inventory_usd(), 0.0)
        max_by_cap = min(per_mkt_avail, global_avail) / s.our_buy_px if s.our_buy_px > 0 else 0
        fill_size = min(size, QUOTE_SIZE_CONTRACTS, max_by_cap)
        if fill_size < 1.0:
            # Not enough cap room — skip (simulates us having posted a 0-size quote)
            return
        # Determine taker/maker: our BUY is taker if our_buy_px >= best_ask (crossing)
        is_taker = s.our_buy_px >= s.best_ask - 1e-9 if s.best_ask > 0 else False
        fee = compute_fee(fill_size, s.our_buy_px, is_taker)
        if is_taker:
            s.fees_paid_taker += fee
        else:
            s.fees_paid_maker += fee
        old_inv = s.inventory
        s.inventory += fill_size
        if s.inventory > 0:
            # Cost basis is pure price (fees tracked separately in realized_pnl)
            s.cost_basis = (s.cost_basis * old_inv + s.our_buy_px * fill_size) / s.inventory
        # Fee is a realized cost (no matching revenue until sell)
        s.realized_pnl -= fee
        s.fills_buy += 1
        s.buy_armed = False
        with open(TRADES_LOG, "a", newline="") as f:
            csv.writer(f).writerow([
                datetime.now(timezone.utc).isoformat(timespec="milliseconds"),
                s.ticker, "BUY", f"{s.our_buy_px:.4f}", f"{fill_size}",
                f"{s.inventory:.0f}", f"{s.realized_pnl:.2f}", s.title,
            ])
        print(f"  🟢 SHADOW BUY  {s.ticker[:32]:<34s} {fill_size:>6.1f}@{s.our_buy_px:.4f}  inv={s.inventory:.0f}", flush=True)
        return

    # SELL fill: taker bought yes at our_sell_px or higher
    if (s.sell_armed and s.our_sell_px > 0 and taker_side == "yes"
            and yes_px >= s.our_sell_px - 1e-9 and s.inventory > 0):
        fill_size = min(size, int(s.inventory), QUOTE_SIZE_CONTRACTS)
        if fill_size <= 0:
            return
        # Determine taker/maker: our SELL is taker if our_sell_px <= best_bid (crossing down)
        is_taker = s.our_sell_px <= s.best_bid + 1e-9 if s.best_bid > 0 else False
        fee = compute_fee(fill_size, s.our_sell_px, is_taker)
        if is_taker:
            s.fees_paid_taker += fee
        else:
            s.fees_paid_maker += fee
        pnl = (s.our_sell_px - s.cost_basis) * fill_size - fee
        s.realized_pnl += pnl
        s.inventory -= fill_size
        s.fills_sell += 1
        s.sell_armed = False
        s.recent_sell_ts.append(time.time())
        with open(TRADES_LOG, "a", newline="") as f:
            csv.writer(f).writerow([
                datetime.now(timezone.utc).isoformat(timespec="milliseconds"),
                s.ticker, "SELL", f"{s.our_sell_px:.4f}", f"{fill_size}",
                f"{s.inventory:.0f}", f"{s.realized_pnl:.2f}", s.title,
            ])
        print(f"  🟢 SHADOW SELL {s.ticker[:32]:<34s} {fill_size:>6.1f}@{s.our_sell_px:.4f}  pnl=${pnl:+.2f}  inv={s.inventory:.0f}", flush=True)


# ── Message routing ────────────────────────────────────────────────

def on_message(ws, raw):
    try:
        msg = json.loads(raw)
    except Exception:
        return
    msg_type = msg.get("type")
    msg_data = msg.get("msg") or {}

    if msg_type == "orderbook_snapshot":
        _debug_dump("orderbook_snapshot", msg)
        ticker = msg_data.get("market_ticker")
        if ticker and ticker in STATES:
            with _LOCK:
                s = STATES[ticker]
                apply_orderbook_snapshot(s, msg_data)
                s.book_updates += 1
                compute_quotes(s)
                log_quote_snapshot(s)
                log_rewards(s)

    elif msg_type == "orderbook_delta":
        _debug_dump("orderbook_delta", msg)
        ticker = msg_data.get("market_ticker")
        if ticker and ticker in STATES:
            with _LOCK:
                s = STATES[ticker]
                apply_orderbook_delta(s, msg_data)
                s.book_updates += 1
                compute_quotes(s)
                log_quote_snapshot(s)
                log_rewards(s)

    elif msg_type == "trade":
        _debug_dump("trade", msg)
        ticker = msg_data.get("market_ticker") or msg_data.get("ticker")
        if ticker and ticker in STATES:
            with _LOCK:
                handle_trade(STATES[ticker], msg_data)

    elif msg_type == "subscribed":
        print(f"  [ws] subscribed ok: {msg.get('msg', {})}", flush=True)

    elif msg_type == "error":
        print(f"  [ws ERROR] {msg}", flush=True)

    elif msg_type == "ok":
        pass  # ack

    else:
        # Unknown message type — log first occurrence for debugging
        pass


def on_error(ws, err):
    print(f"  [ws error] {err}", flush=True)


def on_close(ws, code, msg):
    print(f"  [ws closed] code={code} msg={msg}", flush=True)


def on_open(ws):
    tickers = list(STATES.keys())
    print(f"  [ws open] subscribing to {len(tickers)} markets...", flush=True)
    # Kalshi WS subscribe format
    sub = {
        "id": 1,
        "cmd": "subscribe",
        "params": {
            "channels": ["orderbook_delta", "trade"],
            "market_tickers": tickers,
        },
    }
    ws.send(json.dumps(sub))


# ── Main ───────────────────────────────────────────────────────────

def load_candidates():
    with open(CANDIDATES_PATH) as f:
        data = json.load(f)
    filtered = [m for m in data
                if m.get("yes_bid", 0) > 0 and m.get("yes_ask", 0) > 0
                and m.get("spread_ticks", 0) >= MIN_SPREAD_TICKS
                and m.get("vol_24h", 0) >= 10000]
    filtered.sort(key=lambda x: -x.get("spread_ticks", 0))
    top = filtered[:TOP_N_MARKETS]
    print(f"Loaded {len(top)} candidate markets (top-{TOP_N_MARKETS} by spread):")
    cat_counts = {}
    for m in top:
        category, cap_mult = classify_market(m["ticker"])
        s = MarketShadow(
            ticker=m["ticker"],
            title=m.get("title", "")[:60],
            tick=m.get("tick_step", 0.01),
            vol_24h=m.get("vol_24h", 0),
            category=category,
            cap_multiplier=cap_mult,
        )
        STATES[s.ticker] = s
        cat_counts[category] = cat_counts.get(category, 0) + 1
        per_market_cap = CLIP_USD * cap_mult
        gate = "[DISABLED]" if cap_mult == 0 else f"[cap=${per_market_cap:.0f}]"
        print(f"  {s.ticker:<35s} sp={m['spread_ticks']:.1f}t  tick={s.tick:.4f}  "
              f"vol=${s.vol_24h:,.0f}/d  {category:<16s} {gate}  {s.title[:35]}")
    print(f"\nCategory distribution: {cat_counts}")
    print(f"Global inventory cap: ${GLOBAL_INVENTORY_CAP_USD:.0f}")
    print(f"Turnover gate: auto-liquidate if inv>0 with <{TURNOVER_MIN_SELLS_PER_WINDOW} sells in {TURNOVER_WINDOW_MIN}min")


def ws_run():
    private_key = load_private_key()

    def subprotocol_or_header():
        # Kalshi expects auth via headers on the initial HTTP upgrade request.
        # For WS path, method is "GET" and path is the websocket URL path.
        # Derive path from WS_URL
        from urllib.parse import urlparse
        parsed = urlparse(WS_URL)
        path = parsed.path
        hdrs = sign_request(private_key, "GET", path)
        return [f"{k}: {v}" for k, v in hdrs.items()]

    while not _STOP:
        try:
            ws = websocket.WebSocketApp(
                WS_URL,
                header=subprotocol_or_header(),
                on_open=on_open,
                on_message=on_message,
                on_error=on_error,
                on_close=on_close,
            )
            ws.run_forever(ping_interval=25, ping_timeout=10)
        except Exception as e:
            print(f"  [ws exception] {e}", flush=True)
        if not _STOP:
            print("  [ws] reconnecting in 3s...", flush=True)
            time.sleep(3)


def main():
    if not KEY_ID or not PRIVATE_KEY_PATH:
        raise SystemExit("Missing env vars. Run: source ~/Documents/kalshi_secrets.env")
    ensure_logs()
    load_candidates()
    if not STATES:
        raise SystemExit("No markets loaded.")

    print()
    print("=" * 90)
    print(f"KALSHI SHADOW WS — {len(STATES)} markets — auth-enabled — {datetime.now().isoformat(timespec='seconds')}")
    print("=" * 90)

    ws_thread = threading.Thread(target=ws_run, daemon=True)
    ws_thread.start()

    last_summary = time.time()
    while not _STOP:
        time.sleep(5)
        now = time.time()
        if now - last_summary >= 60:
            last_summary = now
            elapsed_h = (now - _START) / 3600.0
            with _LOCK:
                total_fills = sum(s.fills_buy + s.fills_sell for s in STATES.values())
                total_trades = sum(s.trades_seen for s in STATES.values())
                total_books = sum(s.book_updates for s in STATES.values())
                total_realized = sum(s.realized_pnl for s in STATES.values())
                total_fees_m = sum(s.fees_paid_maker for s in STATES.values())
                total_fees_t = sum(s.fees_paid_taker for s in STATES.values())
                active = sum(1 for s in STATES.values() if s.our_buy_px > 0 or s.our_sell_px > 0)
            print(f"t+{elapsed_h*60:.0f}m  active={active}/{len(STATES)}  "
                  f"books={total_books}  trades={total_trades}  "
                  f"fills={total_fills}  realized=${total_realized:+.2f}  "
                  f"fees(m/t)=${total_fees_m:.2f}/${total_fees_t:.2f}", flush=True)

    # Final summary
    print("\n" + "=" * 90)
    print("FINAL")
    print("=" * 90)
    elapsed_h = (time.time() - _START) / 3600.0
    total_fills = sum(s.fills_buy + s.fills_sell for s in STATES.values())
    total_realized = sum(s.realized_pnl for s in STATES.values())
    print(f"runtime:      {elapsed_h:.2f}h")
    print(f"fills:        {total_fills}")
    print(f"realized P&L: ${total_realized:+.2f}")
    print("\nper-market with fills:")
    for s in sorted(STATES.values(), key=lambda x: -(x.fills_buy + x.fills_sell)):
        if s.fills_buy + s.fills_sell == 0:
            continue
        print(f"  {s.ticker[:32]:<34s} buy={s.fills_buy} sell={s.fills_sell} "
              f"realized=${s.realized_pnl:+.2f} inv={s.inventory:.0f}")


if __name__ == "__main__":
    main()
