"""
KALSHI SHADOW MODE — public-data dry run.

No authentication required. Uses Kalshi's public /orderbook and /trades
endpoints. Polls ~every 3s per market. Computes would-be quotes using the
same logic planned for live_mm, logs hypothetical fills when real trade
prints cross our virtual quote, tracks inventory + P&L + rewards proxy.

Reads candidate markets from kalshi_candidates_v2.json (generated by
diag_kalshi_v2.py). Defaults to top 15 widest-spread markets for signal.

Outputs:
  kalshi_shadow_quotes.csv    snapshot of our quotes + market state every poll
  kalshi_shadow_fills.csv     hypothetical fills (trade crossed our quote)
  kalshi_shadow_rewards.csv   rewards-scoring proxy: distance from best bid/ask
"""

import csv
import json
import os
import signal
import threading
import time
from collections import defaultdict, deque
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Optional

import requests

BASE = "https://api.elections.kalshi.com/trade-api/v2"
CANDIDATES_PATH = os.path.join(os.path.dirname(__file__), "kalshi_candidates_v2.json")
POLL_INTERVAL_S = 3.0
TOP_N_MARKETS = int(os.environ.get("SHADOW_TOP_N", "15"))
MIN_SPREAD_TICKS = 3            # only shadow markets with spread >= 3 ticks
QUOTE_SIZE_CONTRACTS = 100      # how many contracts our virtual quote would post
CLIP_USD = 100.0                 # max $ exposure per side (virtual)

TRADES_LOG = os.path.join(os.path.dirname(__file__), "kalshi_shadow_fills.csv")
QUOTES_LOG = os.path.join(os.path.dirname(__file__), "kalshi_shadow_quotes.csv")
REWARDS_LOG = os.path.join(os.path.dirname(__file__), "kalshi_shadow_rewards.csv")

_STOP = False


def handle_stop(signum, frame):
    global _STOP
    _STOP = True
    print("\nshutdown requested, finishing loop...")


signal.signal(signal.SIGINT, handle_stop)
signal.signal(signal.SIGTERM, handle_stop)


@dataclass
class MarketShadow:
    ticker: str
    title: str
    tick: float
    vol_24h: float
    best_bid: float = 0.0
    best_ask: float = 0.0
    best_bid_size: float = 0.0
    best_ask_size: float = 0.0
    our_buy_px: float = 0.0
    our_sell_px: float = 0.0
    our_buy_size: float = 0.0
    our_sell_size: float = 0.0
    # Hypothetical fill state
    inventory: float = 0.0
    cost_basis: float = 0.0
    realized_pnl: float = 0.0
    fills_buy: int = 0
    fills_sell: int = 0
    buy_armed: bool = True
    sell_armed: bool = True
    # Rewards proxy
    cumulative_distance_score: float = 0.0  # lower = better (closer to best)
    score_samples: int = 0
    # Trade tracking (so we only count new trades since last poll)
    last_trade_id_seen: Optional[str] = None
    # Updates
    updates: int = 0


STATES: Dict[str, MarketShadow] = {}
_LOCK = threading.Lock()
_START = time.time()


def fp(v) -> float:
    try: return float(v)
    except (TypeError, ValueError): return 0.0


def ensure_logs():
    for path, header in [
        (TRADES_LOG, ["timestamp", "ticker", "side", "fill_px", "size",
                      "inventory_after", "realized_pnl", "title"]),
        (QUOTES_LOG, ["timestamp", "ticker", "best_bid", "best_ask",
                      "our_buy", "our_sell", "inventory", "realized_pnl"]),
        (REWARDS_LOG, ["timestamp", "ticker", "distance_from_mid_bid",
                       "distance_from_mid_ask", "normalized_score"]),
    ]:
        if not os.path.exists(path):
            with open(path, "w", newline="") as f:
                csv.writer(f).writerow(header)


def load_candidates() -> List[MarketShadow]:
    if not os.path.exists(CANDIDATES_PATH):
        print(f"ERROR: {CANDIDATES_PATH} not found. Run diag_kalshi_v2.py first.")
        return []
    with open(CANDIDATES_PATH) as f:
        data = json.load(f)
    # Filter + rank by spread_ticks (widest first for cleanest signal)
    filtered = [m for m in data
                if m.get("yes_bid", 0) > 0 and m.get("yes_ask", 0) > 0
                and m.get("spread_ticks", 0) >= MIN_SPREAD_TICKS
                and m.get("vol_24h", 0) >= 10000]
    filtered.sort(key=lambda x: -x.get("spread_ticks", 0))
    top = filtered[:TOP_N_MARKETS]
    print(f"Loaded {len(top)} candidate markets (spread >= {MIN_SPREAD_TICKS}t, vol >= $10k/d, top-{TOP_N_MARKETS} by spread)")
    out = []
    for m in top:
        s = MarketShadow(
            ticker=m["ticker"],
            title=m.get("title", "")[:60],
            tick=m.get("tick_step", 0.01),
            vol_24h=m.get("vol_24h", 0),
            best_bid=m.get("yes_bid", 0),
            best_ask=m.get("yes_ask", 0),
        )
        out.append(s)
        print(f"  {s.ticker:<35s}  sp={m['spread_ticks']:.1f}t  tick={s.tick:.4f}  vol=${s.vol_24h:,.0f}/d  {s.title}")
    return out


def fetch_orderbook(ticker: str) -> Optional[dict]:
    try:
        r = requests.get(f"{BASE}/markets/{ticker}/orderbook", timeout=10)
        r.raise_for_status()
        return r.json().get("orderbook", {})
    except Exception:
        return None


def fetch_recent_trades(ticker: str, min_ts_ms: Optional[int] = None) -> List[dict]:
    """Fetch trades for a market. Returns newest-first. Kalshi /trades endpoint."""
    try:
        params = {"ticker": ticker, "limit": 50}
        if min_ts_ms:
            params["min_ts"] = min_ts_ms
        r = requests.get(f"{BASE}/markets/trades", params=params, timeout=10)
        r.raise_for_status()
        return r.json().get("trades", [])
    except Exception:
        return []


def compute_quotes(s: MarketShadow) -> None:
    """Set our_buy_px / our_sell_px based on current book + strategy."""
    if s.best_bid <= 0 or s.best_ask <= 0:
        s.our_buy_px = 0.0
        s.our_sell_px = 0.0
        return
    spread = s.best_ask - s.best_bid
    tick = s.tick
    if spread < 2 * tick:  # can't post inside, join queue
        s.our_buy_px = round(s.best_bid, 4)
        s.our_sell_px = round(s.best_ask, 4)
    else:
        s.our_buy_px = round(s.best_bid + tick, 4)
        s.our_sell_px = round(s.best_ask - tick, 4)
    # Inventory guard
    if s.inventory * s.best_ask >= CLIP_USD:
        s.our_buy_px = 0.0
    if s.inventory <= 0:
        s.our_sell_px = 0.0
    # Re-arm if rebounded
    if s.buy_armed is False and s.best_ask > s.our_buy_px + tick:
        s.buy_armed = True
    if s.sell_armed is False and s.best_bid < s.our_sell_px - tick:
        s.sell_armed = True


def detect_hypothetical_fills(s: MarketShadow, trades: List[dict]) -> None:
    """If real trades cross our virtual quote, log a hypothetical fill.

    Kalshi trades come with:
      trade_id, ticker, count (size), yes_price (cents 0-100),
      no_price (cents 0-100 = 100 - yes_price), created_time, taker_side ("yes"/"no")

    Fill logic:
      - taker_side == "no": taker SOLD yes at yes_price. Fills our buy if yes_price <= our_buy_px.
      - taker_side == "yes": taker BOUGHT yes at yes_price. Fills our sell if yes_price >= our_sell_px.
    """
    if not trades:
        return

    # On first poll, just bookmark the newest trade ID — don't retroactively "fill" on history.
    newest_id = trades[0].get("trade_id") or trades[0].get("id")
    if s.last_trade_id_seen is None:
        s.last_trade_id_seen = newest_id
        return

    if s.our_buy_px <= 0 and s.our_sell_px <= 0:
        s.last_trade_id_seen = newest_id
        return

    # Process only trades newer than last seen. Trades list is newest-first; iterate
    # reversed so we apply in chronological order.
    for t in reversed(trades):
        tid = t.get("trade_id") or t.get("id")
        if tid == s.last_trade_id_seen:
            continue
        yes_price_cents = t.get("yes_price")
        if yes_price_cents is None:
            continue
        yes_px = float(yes_price_cents) / 100.0   # convert cents to dollars
        if yes_px <= 0 or yes_px >= 1.0:
            continue
        size = fp(t.get("count") or t.get("size"))
        if size <= 0:
            continue
        taker_side = (t.get("taker_side") or "").lower()

        # BUY fill: taker sold yes at our_buy_px or lower
        if (s.buy_armed and s.our_buy_px > 0 and taker_side == "no"
                and yes_px <= s.our_buy_px + 1e-9):
            fill_size = min(size, QUOTE_SIZE_CONTRACTS)
            old_inv = s.inventory
            s.inventory += fill_size
            if s.inventory > 0:
                s.cost_basis = (s.cost_basis * old_inv + s.our_buy_px * fill_size) / s.inventory
            s.fills_buy += 1
            s.buy_armed = False
            with open(TRADES_LOG, "a", newline="") as f:
                csv.writer(f).writerow([
                    datetime.now(timezone.utc).isoformat(timespec="seconds"),
                    s.ticker, "BUY", f"{s.our_buy_px:.4f}", f"{fill_size:.0f}",
                    f"{s.inventory:.0f}", f"{s.realized_pnl:.2f}", s.title,
                ])
            print(f"  🟢 SHADOW BUY  {s.ticker[:30]}  {fill_size:.0f}@{s.our_buy_px:.4f}  inv={s.inventory:.0f}")

        # SELL fill: taker bought yes at our_sell_px or higher
        elif (s.sell_armed and s.our_sell_px > 0 and taker_side == "yes"
                and yes_px >= s.our_sell_px - 1e-9 and s.inventory > 0):
            fill_size = min(size, s.inventory, QUOTE_SIZE_CONTRACTS)
            pnl = (s.our_sell_px - s.cost_basis) * fill_size
            s.realized_pnl += pnl
            s.inventory -= fill_size
            s.fills_sell += 1
            s.sell_armed = False
            with open(TRADES_LOG, "a", newline="") as f:
                csv.writer(f).writerow([
                    datetime.now(timezone.utc).isoformat(timespec="seconds"),
                    s.ticker, "SELL", f"{s.our_sell_px:.4f}", f"{fill_size:.0f}",
                    f"{s.inventory:.0f}", f"{s.realized_pnl:.2f}", s.title,
                ])
            print(f"  🟢 SHADOW SELL {s.ticker[:30]}  {fill_size:.0f}@{s.our_sell_px:.4f}  pnl=${pnl:+.2f}  inv={s.inventory:.0f}")

    s.last_trade_id_seen = newest_id


def log_rewards_proxy(s: MarketShadow) -> None:
    """Rewards scoring proxy: how close our quote is to top-of-book."""
    if s.best_bid <= 0 or s.best_ask <= 0:
        return
    mid = (s.best_bid + s.best_ask) / 2.0
    bid_dist = (mid - s.our_buy_px) if s.our_buy_px > 0 else 999
    ask_dist = (s.our_sell_px - mid) if s.our_sell_px > 0 else 999
    # Normalized score: closer to mid = better. Scale by tick so markets compare.
    norm = ((bid_dist + ask_dist) / 2.0) / max(s.tick, 1e-9)
    s.cumulative_distance_score += norm
    s.score_samples += 1
    with open(REWARDS_LOG, "a", newline="") as f:
        csv.writer(f).writerow([
            datetime.now(timezone.utc).isoformat(timespec="seconds"),
            s.ticker, f"{bid_dist:.4f}", f"{ask_dist:.4f}", f"{norm:.2f}",
        ])


def log_quote_snapshot(s: MarketShadow) -> None:
    with open(QUOTES_LOG, "a", newline="") as f:
        csv.writer(f).writerow([
            datetime.now(timezone.utc).isoformat(timespec="seconds"),
            s.ticker, f"{s.best_bid:.4f}", f"{s.best_ask:.4f}",
            f"{s.our_buy_px:.4f}", f"{s.our_sell_px:.4f}",
            f"{s.inventory:.0f}", f"{s.realized_pnl:.2f}",
        ])


def poll_market(s: MarketShadow) -> None:
    ob = fetch_orderbook(s.ticker)
    if ob:
        # Kalshi orderbook format: 'yes' (buy side for YES) + 'no' (which = ask side for YES at 100-no_bid)
        yes_side = ob.get("yes") or []
        no_side = ob.get("no") or []
        if yes_side:
            best = max(yes_side, key=lambda x: int(x[0]))
            s.best_bid = int(best[0]) / 100.0
            s.best_bid_size = int(best[1])
        if no_side:
            # Best NO bid = lowest YES ask equivalent: yes_ask = 1 - no_bid
            best_no = max(no_side, key=lambda x: int(x[0]))
            no_bid = int(best_no[0]) / 100.0
            s.best_ask = 1.0 - no_bid
            s.best_ask_size = int(best_no[1])
        s.updates += 1

    compute_quotes(s)
    log_quote_snapshot(s)
    log_rewards_proxy(s)

    # Trades — detect hypothetical fills
    trades = fetch_recent_trades(s.ticker)
    if trades:
        detect_hypothetical_fills(s, trades)


def main():
    ensure_logs()
    shadows = load_candidates()
    if not shadows:
        return
    for s in shadows:
        STATES[s.ticker] = s

    print()
    print("=" * 90)
    print(f"KALSHI SHADOW MODE STARTED — {len(STATES)} markets, poll={POLL_INTERVAL_S}s")
    print("=" * 90)

    last_console = time.time()

    while not _STOP:
        loop_start = time.time()
        for ticker, s in list(STATES.items()):
            if _STOP:
                break
            poll_market(s)
            time.sleep(0.2)  # per-market delay to spread rate

        now = time.time()
        if now - last_console >= 60:
            last_console = now
            elapsed_h = (now - _START) / 3600.0
            total_fills = sum(s.fills_buy + s.fills_sell for s in STATES.values())
            total_realized = sum(s.realized_pnl for s in STATES.values())
            print(f"t+{elapsed_h*60:.0f}m  fills={total_fills}  realized=${total_realized:+.2f}")

        # Maintain poll interval
        elapsed = time.time() - loop_start
        if elapsed < POLL_INTERVAL_S * len(STATES):
            time.sleep(max(0, POLL_INTERVAL_S * len(STATES) - elapsed))

    # Final summary
    print("\n" + "=" * 90)
    print("FINAL SUMMARY")
    print("=" * 90)
    elapsed_h = (time.time() - _START) / 3600.0
    total_fills = sum(s.fills_buy + s.fills_sell for s in STATES.values())
    total_realized = sum(s.realized_pnl for s in STATES.values())
    total_updates = sum(s.updates for s in STATES.values())
    print(f"runtime:         {elapsed_h:.2f}h")
    print(f"total updates:   {total_updates}")
    print(f"total fills:     {total_fills}")
    print(f"realized P&L:    ${total_realized:+.2f}")
    print()
    print("Per-market (fills > 0):")
    for s in sorted(STATES.values(), key=lambda x: -(x.fills_buy + x.fills_sell)):
        if s.fills_buy + s.fills_sell == 0:
            continue
        avg_dist = s.cumulative_distance_score / max(s.score_samples, 1)
        print(f"  {s.ticker[:30]:<32s}  buy={s.fills_buy} sell={s.fills_sell} "
              f"realized=${s.realized_pnl:+.2f}  inv={s.inventory:.0f}  "
              f"avg_dist={avg_dist:.2f}t")

    # Rewards signal
    print("\nRewards-proxy (lower = better, quotes closer to mid):")
    by_score = sorted(
        [(t, s.cumulative_distance_score / max(s.score_samples, 1), s.score_samples)
         for t, s in STATES.items() if s.score_samples > 0],
        key=lambda x: x[1],
    )
    for t, score, n in by_score[:10]:
        print(f"  {t[:35]:<37s}  avg={score:.2f}t  samples={n}")

    print(f"\nlogs: {TRADES_LOG}, {QUOTES_LOG}, {REWARDS_LOG}")


if __name__ == "__main__":
    main()
